# Generated by Django 2.2.20 on 2021-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(choices=[('R', 'RealStar'), ('E', 'ElectroCo'), ('P', 'Papsi')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
